version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: sherlock
    main: ./cmd/sherlock
    binary: sherlock
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: sherlock
    builds:
      - sherlock
    name_template: "sherlock_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - image_templates:
      - "ghcr.io/rahulkosamkar/sherlock:{{ .Version }}"
      - "ghcr.io/rahulkosamkar/sherlock:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: rahulkosamkar
    name: sherlock
  prerelease: auto
