apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sherlock.fullname" . }}
  labels:
    {{- include "sherlock.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-dsn: {{ .Values.postgres.dsn | b64enc | quote }}
  slack-bot-token: {{ .Values.slack.botToken | b64enc | quote }}
  slack-app-token: {{ .Values.slack.appToken | b64enc | quote }}
  slack-signing-secret: {{ .Values.slack.signingSecret | b64enc | quote }}
  s3-access-key: {{ .Values.objectstore.accessKey | b64enc | quote }}
  s3-secret-key: {{ .Values.objectstore.secretKey | b64enc | quote }}
  grafana-hmac-secret: {{ .Values.receivers.grafana.hmacSecret | b64enc | quote }}
  llm-api-key: {{ .Values.llm.apiKey | b64enc | quote }}
  git-token: {{ .Values.git.token | b64enc | quote }}
